language: node_js
script:
  - npm run test:ci
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    # $ travis encrypt $(heroku auth:token)
    # ›   Warning: token will expire 11/06/2019
    secure: a2ZgHpgs87PNxigJp+9POjv/tJA99qZ9day/THwo6WT+YR5KaVigwngmpWIpD6Nuw+YeQZyqEHhDGljPvOXxNRZjPjZyhpVgoa2mX8nHIN8tu6mH1BZMOmx/Oq67OrTqIKsm18ur10Unbodgu3eYG+4Q5glCJw3KabtTgMnZCsM2CTmh0onvwig7dVPHrTpB9UJfG1IhHwC9YsKiAgpithRuEnqH9PfyhsWhQAsPDrIUwS9HxRsE22k85JH9OmThxuqfE2ee2c+kin3Vkc1nTyz599JHPPefGNRXAOiKh2/veBuiNvdsaYQU6nHam4EbI6x55AzMOGoJz579W5kW/uVqwaLE98tc2r3PykvvIroQWKaS7aoaGNNHAWPAlhGBQvDWtaSZy+SLy8e7eo39lm0mVrXvJbabZu7lfWaS1CXBRMVxSwnn9DQZvaxlvXDhlCBlguAD8Fgq1Y+Cl6jc3+jzBG7nqFKp4xllAWew7u1U2D8PgzxmHzksLRnPkitJIwDPXGIGtWk4Je81qQgNlEoMoaXVq3WgnujLP4cZRkOhT7LfzuJUgW8ypHItkPNI2j0KJ8Tqnk4IpGOZiSgevWgJE7KbC8xxd4m89Mm+oF7qbIHDVHoIoXn5OL3aM/WBFBm0YYqdN65y3+Ot1CGt8pEVZ7LUxgz1QrX9DDRsWDM=
  app: draftail-playground
  on:
    repo: thibaudcolas/draftail-playground
